services:
  - type: web
    name: FlexCommerce
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py tailwind install
      python manage.py tailwind build
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ecomerce.wsgi:application
    envVars:
      DJANGO_SETTINGS_MODULE: ecomerce.settings
    build:
      languages:
        nodejs: 20
